### ISSUE TITLE
OSX platform missing files

### ISSUE THREAD

**Issue by kdubb** [gabriel/MPMessagePack#16]
In `MPMessagePack.h` there's a guard to include XPC related files only for OSX.  None of those files are included with the pod.

Removing the OS X specific headers allows it to build and be used properly. It looks like the files are just missing from the podspec.

**Comment by gabriel** [comment]
They are in the podspec?

**Comment by kdubb** [comment]
Yes. Apologies for not closing this last night.  I'm not sure what went wrong but after I looked and your pod spec (which clearly showed the files as included).  I deleted my pods directory and re-ran `pod install`.  All was well after that!.  Seems it was a CP hiccup.
