### ISSUE TITLE
iOS 11 and runtime warning “Class MPRequest is implemented in both…”

### ISSUE THREAD

**Issue by mikemorton-tm** [gabriel/MPMessagePack#22]
Our app uses MPMessagePack version 1.3.5.

When we run under iOS 11 (simulator or device), the console shows:
`objc[82583]: Class MPRequest is implemented in both /Applications/Xcode-9.0-beta-5.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/MediaPlayer.framework/MediaPlayer (0x1215b9910) and /Users/mike/Library/Developer/CoreSimulator/Devices/0C89D1F2-C4DD-4547-B534-A8D9EE607610/data/Containers/Bundle/Application/7D76C94B-AA79-436A-B3F2-DCDAAE46B485/Mojo.app/Frameworks/MPMessagePack.framework/MPMessagePack (0x109820510). One of the two will be used. Which one is undefined.`

So far, everything seems to work fine, but we worry that “which one is undefined” will bite us some time after we ship.

Anyone else seeing this? Any plans to rename the class and put out a new version and pod?

Thanks!

**Comment by gabriel** [comment]
Sure renamed to `MPRequestor` and released new pod version

**Comment by mikemorton-tm** [comment]
Wow; thanks for the superfast turnaround.
