### ISSUE TITLE
Carthage build fails

### ISSUE THREAD

**Issue by flockoffiles** [gabriel/MPMessagePack#25]
If I do carthage update, the build fails because Carthage tries to build all the targets, including the the target which uses Pods. I can only make it build if I manually run pod install inside Carthage/Checkouts/MPMessagePack and then run carthage build

**Comment by flockoffiles** [comment]
When I open the project, there is no separate target for Carthage to build, and the MPMessagePack iOS target links with a library that is build by cocoapods...
So, in other words, it's not clear how MPMessagePack can be built with Carthage alone...

**Comment by gabriel** [comment]
Oops, yeah the xcodeproj had pod stuff in it (which it shouldn't have). I removed and pushed new version, and tested it and it should now work.
