### ISSUE TITLE
Could you make cmp.h a Public header?

### ISSUE THREAD

**Issue by flockoffiles** [gabriel/MPMessagePack#26]
Could you mark cmp.h a Public header in Xcode target membership (for both targets)?
Otherwise, the header is NOT copied to the resulting .framework, and it fails to compile when built with Carthage and imported into another project.

Marking  cmp.h as Public (and not as 'Project') will cause the header to appear in the Headers subfolder inside MPMessagePack.framework

Thanks!

**Comment by gabriel** [comment]
Marked public and pushed new version
