### ISSUE TITLE
SPM failed to resolve dependencies because of the unstable-version package `ghodictionary`.

### ISSUE THREAD

**Issue by greenchiu** [gabriel/MPMessagePack#34]
Hi,

I've encountered an issue with SPM (Swift Package Manager). The error message I received is as follows:

> Failed to resolve dependencies Dependencies could not be resolved because package 'mpmessagepack' is required using a stable-version but 'mpmessagepack' depends on an unstable-version package 'ghodictionary' and root depends on 'mpmessagepack' 1.6.0.

Could you help about that? Thank you.

**Comment by ethanhuang-ui** [comment]
+1 for this. Suggest adding a new version tag on the latest commit(5e61d2a98fc548101eafd1934a6b09261184db1c).

**Comment by gabriel** [comment]
Tagged 1.6.1, does that fix it?

**Comment by ethanhuang-ui** [comment]
Yes. The issue is resolved. Thank you.

1. Set version 1.6.1 in Xcode
> <img width="766" alt="CleanShot 2023-10-05 at 12 04 28@2x" src="https://github.com/gabriel/MPMessagePack/assets/85927129/f2d1020f-6032-4cf5-900c-47924a44f7fa">

2. Xcode's Project navigator panel shows the correct version without any errors.
> <img width="185" alt="CleanShot 2023-10-05 at 12 04 22@2x" src="https://github.com/gabriel/MPMessagePack/assets/85927129/d62be7af-ea53-43a8-9b8b-0fc3ab855393">

> <img width="178" alt="CleanShot 2023-10-05 at 12 09 50@2x" src="https://github.com/gabriel/MPMessagePack/assets/85927129/fdfff0df-7e47-4715-a626-e2a252e8be96">


3. Package.resolved file updated
> <img width="524" alt="CleanShot 2023-10-05 at 12 05 34@2x" src="https://github.com/gabriel/MPMessagePack/assets/85927129/738fd42e-b451-4721-919f-a8d065d10248">

**Comment by greenchiu** [comment]
Thanks for help. The issue is resolved.
