### ISSUE TITLE
Memory leak in readObject

### ISSUE THREAD

**Issue by damiantrimboli** [gabriel/MPMessagePack#8]
Hi Gabriel, 
I'm using your library. Very nice indeed :)

But i'm having a problem, I think the readObject method is leaking some NSMutableData inside.
For example, if I call this a lot of times in a loop without even storing the NSDictionary, the memory keeps increasing.

 var reader:MPMessagePackReader = MPMessagePackReader(data: dataChannel);
 reader.readObject(nil) as! NSDictionary;

And there is no way of freeing it. 
Instruments found these as "Zombies" if you profile it.

Could you check this please?
Thank you so much.

Damian.

**Comment by gabriel** [comment]
Doing a test and profiling with Zombies and Leaks doesn't show anything for me... Do you have a reproducible test case?

**Comment by gabriel** [comment]
When you are testing it do you have zombies enabled because then all objects leak (on purpose)

**Comment by damiantrimboli** [comment]
I could find a way to easily reproduce what is happening to me, it seems to happen inside a loop in a background thread. You can check test1 (no leak), test2 (moderate leak), test3 (big leak).

After any step of the loop, there's no need to keep any of the objects created inside it (dictionaries, strings, etc etc). With test1, the created dictionary doesn't keep in memory as expected. But in the other 2 tests, memory created there never gets released and eventually crash the application cause of memory pressure.

Can you help me? This is very important. I'm using MsgPack in a Zmq client which needs to be running in a loop in a background thread (since I keep receiving multiple msgpack'd messages per second).

Thank you in advance!
```javascript

 var subscriber_queue: dispatch_queue_t  = dispatch_queue_create( "subQueue", nil);

 func main() {

        dispatch_async(subscriber_queue) { [weak self] in
            autoreleasepool {
                self!.test1() // test2()  test3()
            }
        }
    }

public static func test1()
    {
// No leak here
        var dict = ["YYZ": "Pearson", "DUB1": "Dublin", "DUB2": "Dublin", "DUB3": "Dublin", "DUB4": "Dublin", "DUB5": "Dublin", "DUB6": "Dublin", "DUB7": "Dublin"]        
    }

public static func test2()
    {
        var dict = ["YYZ": "Pearson", "DUB1": "Dublin", "DUB2": "Dublin", "DUB3": "Dublin", "DUB4": "Dublin", "DUB5": "Dublin", "DUB6": "Dublin", "DUB7": "Dublin"]

        var data = (dict as NSDictionary).mp_messagePack(); // This is leaking
    }

public static func test3()
    {
        var dict = ["YYZ": "Pearson", "DUB1": "Dublin", "DUB2": "Dublin", "DUB3": "Dublin", "DUB4": "Dublin", "DUB5": "Dublin", "DUB6": "Dublin", "DUB7": "Dublin"]

        var data = (dict as NSDictionary).mp_messagePack(); // Leak

        var reader:MPMessagePackReader = MPMessagePackReader(data: data); // No leak

        var obj:NSDictionary = reader.readObject(nil) as! NSDictionary; // More leaking
    }

```

**Comment by gabriel** [comment]
can you package it up as a project?

**Comment by damiantrimboli** [comment]
Yes, here it is. Hope it gelps

**Comment by damiantrimboli** [comment]
https://drive.google.com/file/d/0B8EoqT4Isd_vdExfeTFWOGlaT1E/view?usp=sharing

**Comment by gabriel** [comment]
do you need the autoreleasepool to be inside the while loop? otherwise it's never being drained?

**Comment by gabriel** [comment]
Yeah move that into the while and it doesn't leak..

```objc
while (true) {
  autoreleasepool {
    self!.test();
  } 
}
```
