### ISSUE TITLE
Support extension types

### ISSUE THREAD

**Issue by gabriel** [gabriel/MPMessagePack#9]
```
case CMP_TYPE_EXT8:
case CMP_TYPE_EXT16:
case CMP_TYPE_EXT32:
case CMP_TYPE_FIXEXT1:
case CMP_TYPE_FIXEXT2:
case CMP_TYPE_FIXEXT4:
case CMP_TYPE_FIXEXT8:
case CMP_TYPE_FIXEXT16:
```

**Comment by frmdstryr** [comment]
Bump. Any updates on this?

**Comment by frmdstryr** [comment]
Nevermind,  I was able to make it just return a dict https://github.com/frmdstryr/MPMessagePack

**Comment by gabriel** [comment]
Submit a pull request, I'll pull it in?

**Comment by gabriel** [comment]
Github made this easy.. Pulled into version 1.4.2

**Comment by frmdstryr** [comment]
Sorry for not responding, was on vacation. Thanks for pulling it in!
